# This is a config for E2B sandbox template.
# You can use template ID (q8x28a5e65yqc0adf7vx) or template name (vara-vibe-nextjs-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vara-vibe-nextjs-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vara-vibe-nextjs-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vara-vibe-nextjs-2')

team_id = "8ebcddd6-1080-46a4-9f60-8112e11e2776"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vara-vibe-nextjs-2"
template_id = "q8x28a5e65yqc0adf7vx"
